### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by mtnezm** [slackspace-io/slackwatch#3]
Hello,

Are there any plans to add a chart for this application so it can be deployed using Helm? 

Thanks!

**Comment by slackspace-io** [comment]
I can try to get a helm chart this tonight/weekend!

**Comment by slackspace-io** [comment]
@mtnezm the latest release has helm included :) 

Helm Documentation: https://slackspace-io.github.io/slackwatch/installation.html#helm 

Can also find the details of which annotations to enable slackwatch to watch a given deployment here: https://slackspace-io.github.io/slackwatch/workload_annotations.html

Let me know if any issues! :latest or :v0.3.4 is what you'll want to use.

**Comment by slackspace-io** [comment]
Doh, thanks! Cleaned up index.yaml to remove the missing v0.1.1 package from the index.

Thanks for the confirmation/feedback!
